# Generated by Django 4.0 on 2023-10-09 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_category_name_en_category_name_ru_category_name_uz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='audio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='news',
            name='img',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='news',
            name='video',
            field=models.BooleanField(default=False),
        ),
    ]
